"""Update Rogers Finance Data Agent instructions in place.

After the user adds the data source in the portal, this fills in:
  - Files/Config/draft/stage_config.json  -> aiInstructions
  - Files/Config/draft/semantic-model-*/datasource.json -> dataSourceInstructions,
                                                            userDescription

Preserves the rest of each file untouched (metadata, elements,
csdl_relationships, etc. are generated by Fabric on data-source add and
must not be overwritten).

Re-runnable: each pass overwrites the instructions with whatever is in this
file, so iterate the prompts here and re-run.
"""
from __future__ import annotations

import base64, json, subprocess, time, urllib.request, urllib.error, uuid
from pathlib import Path

ROOT = Path(__file__).parent
STACK = json.loads((ROOT / "stack_finance.json").read_text())
WS = STACK["workspace_id"]
AGENT = STACK["data_agent_id"]
AZ = r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin\az.cmd"
API = "https://api.fabric.microsoft.com"


# ---- The actual instructions ---------------------------------------------

AI_INSTRUCTIONS = """You are the Rogers Finance Data Agent. Audience: Finance leadership, FP&A, and business partners. Tone: senior, concise, exec-ready.

Response structure (3 short bullets, never more):
  1. The HEADLINE NUMBER with its dimension and time (e.g. "ARPU was $166.25 in Jun 2026, up 6.0% YoY").
  2. WHERE the action is (Product or Region) - one bullet only.
  3. SO WHAT - one sentence. Either a trend call, an anomaly flag, or a follow-up suggestion.

Number style:
  - Dollars: round to cents on per-unit metrics ($166.25), millions on revenue ($2,656.6M).
  - Percentages: one decimal (-1.1%, +0.7%).
  - Subscribers / counts: comma-thousands, no decimals (15,979,233).

Measure discipline:
  - When asked about ARPU, ALWAYS use the certified [ARPU] measure on the Revenue table. Never re-derive from list_price.
  - For revenue trend, use [Revenue YoY %] and [Revenue MoM %].
  - For per-product ARPU, filter [ARPU] by Product[Product Name].
  - For per-region ARPU, filter [ARPU] by Region[Region Name] or Region[Province].

Time intelligence:
  - Default time grain is monthly. Use 'Date'[Month Start] for any DATEADD / SAMEPERIODLASTYEAR / TOPN-by-date logic.
  - "Latest month" = MAX('Date'[Month Start]). The current model ends at 2026-06.
  - "Last quarter" = 'Date'[Year-Quarter] = 2026-Q2 (Apr-Jun 2026).
  - "Last year" = 'Date'[Fiscal Year] one less than latest.

Anomaly awareness (preloaded for the demo):
  - Product "Wireless Prepaid" ARPU dipped from ~$29.39 in Mar 2026 to $24.71 in Apr 2026 (a 16% drop), then recovered to $26.81 in May and $29.12 in Jun (back near baseline). If a user asks about Wireless Prepaid, April 2026, or unusual ARPU movements, surface this proactively.
  - Some Enterprise products (Private 5G Networks, Dedicated Internet Access) show very high per-line ARPU ($12K-$83K/mo) because these are per-contract / per-site, not per-consumer subscribers. If asked about these, explain the per-contract nature.

Guardrails:
  - This model has 24 months of data ending Jun 2026. Refuse to answer questions about dates outside this window.
  - This is NOT a GAAP financial statement. For audited / regulatory figures, point the user to Rogers' official IR disclosures.
  - If a user asks for data not in this model (customer-level PII, segment, channel, churn, costs), say so plainly and don't guess.

Demo hook (use when relevant, not on every answer):
  "This number is the certified [ARPU] defined ONCE in the rogers_finance semantic model. The same value flows to Excel pivots, Power BI reports, and this agent - and it would update everywhere if Finance changed the definition tomorrow."
"""

DATA_SOURCE_INSTRUCTIONS = """Certified Rogers Finance semantic model on Microsoft Fabric Direct Lake.

This is the SINGLE SOURCE OF TRUTH for revenue, subscribers, and ARPU across Rogers product lines. Anyone asking Finance questions should land here.

Star schema (4 tables - kept deliberately simple for the demo):
  Revenue (fact)  - monthly, by product x region. Hidden columns: [Amount] (revenue $), [Avg Subscribers]. Use the measures below, never SUM the raw columns.
  Product (dim)   - product or plan name and revenue type (Subscription / Advertising / Tickets / Project).
  Region  (dim)   - 12 Canadian regions with province code (ON/QC/BC/AB/etc.).
  Date    (dim)   - 24 monthly rows ending Jun 2026. Use [Month Start] for time intelligence; [Month] is the display label.

Certified measures (USE THESE, never re-derive):
  Revenue:    [Revenue], [Revenue (Millions)], [Revenue MoM %], [Revenue YoY %]
  Subs:       [Average Subscribers]
  ARPU (hero): [ARPU] = DIVIDE([Revenue], [Average Subscribers])
              [ARPU MoM %], [ARPU YoY %]

Reconciliation rule:
  [ARPU] = SUM(Revenue[Amount]) / SUM(Revenue[Avg Subscribers]).
  This reconciles to zero delta - presenter can defend it on stage.

Joins (ManyToOne, single-direction):
  Revenue.'Date Key'    -> Date.'Date Key'
  Revenue.'Product Id'  -> Product.'Product Id'
  Revenue.'Region Id'   -> Region.'Region Id'

Note on per-product ARPU magnitude:
  Some Enterprise products show very high per-line ARPU ($12K-$83K/mo) because each "subscriber" is a contract or site (Private 5G Networks, Dedicated Internet Access), not a consumer end-user. Wireless Postpaid / Prepaid ARPU ($30-$90/mo) is the consumer-comparable range.

Known anomaly (for demo grounding):
  Product "Wireless Prepaid" ARPU dipped Mar 2026 ($29.39) -> Apr 2026 ($24.71, -16%) -> May ($26.81) -> Jun ($29.12, recovery). If a question touches Wireless Prepaid, Q2 2026, or unusual ARPU movement, surface this.
"""

USER_DESCRIPTION = "Certified Rogers Finance star schema - revenue, subscribers, ARPU, churn, costs, margin. Single source of truth across Wireless, Cable & Home, Media, Enterprise. 24 months ending 2026-06. ARPU is the hero metric."

# Guardrail for the auto-attached raw lakehouse SQL endpoint. We don't want
# the agent answering Finance questions by writing SQL against raw columns
# when the certified semantic model has measures that already do the math.
LAKEHOUSE_GUARDRAIL_INSTRUCTIONS = """Raw Delta tables behind the rogers_finance certified semantic model. DO NOT use this source for Finance metrics - the semantic model 'rogers_finance' has certified measures ([ARPU], [Revenue], [Gross Margin %], etc.) that already encode the right business logic, naming, and reconciliation rules.

When to use this source:
  - Ad-hoc table inspection / row counts / schema sanity checks
  - Data quality questions (nulls, duplicates, refresh recency)
  - One-off SQL the semantic model genuinely can't express (rare)

When NOT to use this source:
  - ANY question about revenue, ARPU, subscribers, churn, margin, EBITDA, CAC, or net adds - use the semantic model instead
  - Per-BU / per-region / per-segment aggregations - the semantic model already has these as measures
  - Time-trend questions - the semantic model has time intelligence pre-built

If a user asks a Finance metric question, route the answer through the semantic model. Only fall back to raw SQL here if the model genuinely doesn't have a matching measure."""

LAKEHOUSE_USER_DESCRIPTION = "Raw Delta tables behind rogers_finance. Prefer the certified semantic model for any Finance metric question. Use this only for table inspection and data-quality queries."


# ---- HTTP / LRO helpers --------------------------------------------------

def tok():
    return subprocess.check_output(
        [AZ, "account", "get-access-token", "--resource", API,
         "--query", "accessToken", "-o", "tsv"]).decode().strip()


def call(method, url, body=None):
    h = {"Authorization": f"Bearer {tok()}",
         "Content-Type": "application/json",
         "ActivityId": str(uuid.uuid4())}
    data = json.dumps(body).encode() if isinstance(body, dict) else body
    req = urllib.request.Request(url, headers=h, method=method, data=data)
    try:
        with urllib.request.urlopen(req, timeout=300) as r:
            return r.status, dict(r.headers), r.read().decode()
    except urllib.error.HTTPError as e:
        return e.code, dict(e.headers), e.read().decode()


def poll(loc, attempts=40, delay=3):
    for _ in range(attempts):
        time.sleep(delay)
        s, h, b = call("GET", loc)
        try:
            st = json.loads(b).get("status")
        except Exception:
            st = None
        if st == "Succeeded":
            return True, loc.rstrip("/") + "/result"
        if st == "Failed":
            print(f"  FAILED: {b[:600]}")
            return False, None
    return False, None


def get_definition():
    s, h, b = call("POST",
                   f"{API}/v1/workspaces/{WS}/items/{AGENT}/getDefinition")
    if s != 202:
        raise RuntimeError(f"getDefinition status={s} body={b[:300]}")
    ok, result_url = poll(h.get("Location") or h.get("location"))
    if not ok:
        raise RuntimeError("getDefinition poll failed")
    sr, hr, br = call("GET", result_url)
    return json.loads(br)["definition"]


def b64(o_or_s):
    if isinstance(o_or_s, (dict, list)):
        s = json.dumps(o_or_s, indent=2)
    else:
        s = o_or_s
    return base64.b64encode(s.encode("utf-8")).decode("ascii")


# ---- Main update flow ----------------------------------------------------

def main():
    print("Fetching current agent definition...")
    definition = get_definition()
    parts = definition.get("parts", [])
    print(f"  {len(parts)} parts")

    new_parts = []
    touched = []
    for p in parts:
        path = p["path"]
        decoded = base64.b64decode(p["payload"]).decode("utf-8", errors="replace")

        # Update stage_config (top-level AI instructions)
        if path.endswith("stage_config.json"):
            obj = json.loads(decoded)
            obj["aiInstructions"] = AI_INSTRUCTIONS
            new_parts.append({"path": path, "payload": b64(obj),
                              "payloadType": "InlineBase64"})
            touched.append((path, "aiInstructions updated"))
            continue

        # Update the semantic-model data source (the certified one)
        if path.endswith("datasource.json") and "semantic-model" in path:
            obj = json.loads(decoded)
            obj["dataSourceInstructions"] = DATA_SOURCE_INSTRUCTIONS
            obj["userDescription"] = USER_DESCRIPTION
            new_parts.append({"path": path, "payload": b64(obj),
                              "payloadType": "InlineBase64"})
            touched.append((path, "dataSourceInstructions + userDescription updated"))
            continue

        # Guardrail on the raw lakehouse source (don't bypass the model)
        if path.endswith("datasource.json") and "lakehouse" in path:
            obj = json.loads(decoded)
            obj["dataSourceInstructions"] = LAKEHOUSE_GUARDRAIL_INSTRUCTIONS
            obj["userDescription"] = LAKEHOUSE_USER_DESCRIPTION
            new_parts.append({"path": path, "payload": b64(obj),
                              "payloadType": "InlineBase64"})
            touched.append((path, "lakehouse guardrail instructions applied"))
            continue

        # All other parts: pass through unchanged
        new_parts.append(p)

    if not touched:
        print("ERROR: No instructions targets found - did portal add complete?")
        return

    print("\nUpdating:")
    for path, what in touched:
        print(f"  {path}")
        print(f"    -> {what}")

    payload = {"definition": {"parts": new_parts}}
    print(f"\nPushing updateDefinition ({len(new_parts)} parts total)...")
    s, h, b = call("POST",
                   f"{API}/v1/workspaces/{WS}/items/{AGENT}/updateDefinition",
                   body=payload)
    print(f"  status={s}")
    if s == 202:
        ok, _ = poll(h.get("Location") or h.get("location"))
        print(f"  poll: {'OK - instructions live' if ok else 'FAIL'}")
    elif s in (200, 201):
        print("  OK (sync)")
    else:
        print(f"  ERROR: {b[:600]}")


if __name__ == "__main__":
    main()
